[project_id]
project = sasisaidivi

[bucket_names]
bucket_name = synthetic_data_sasi
bucket_old_name = synthetic_old_data_sasi
synthetic_bucket = gs://synthetic_data_sasi
location = US
storage_class = STANDARD

[datasets]
location = US
raw_dataset = raw_synthetic
refine_dataset = refine_synthetic
auth_views = auth_views_synthetic
audit = audit_synthetic

[audit_tables]
raw_audit = synthetic_raw_audit
refine_audit = synthetic_refine_audit
